_extends: .github

branches:
  - name: my-solution
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts:
          - quality-checks
          - deploy-and-tests
      required_signatures: false
      enforce_admins:
      required_linear_history: true
      restrictions:
      allow_force_pushes:
      allow_deletions: false
      required_conversation_resolution: true

repository:
  is_template: true
