# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy and test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - .github/workflows/deploy-and-test.yml
      - src/**
      - tests/**
      - tf/**
      - .aws/**
      - docker-compose.yml
defaults:
  run:
    shell: bash -Eeuo pipefail -x {0}
jobs:
  deploy-and-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Run Terraform
        run: docker-compose run --rm terraform-run
      - name: Run AWS CLI
        run: docker-compose run --rm aws sts get-caller-identity --output text --query Arn
      - name: Sync datasets
        run: docker-compose run --rm tests -u
      - name: Tests
        run: docker-compose run --rm tests
